// <auto-generated />
using System;
using System.Collections.Generic;
using CapituloZero.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811173941_AddUserTypesAndActiveType")]
    partial class AddUserTypesAndActiveType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Artefato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_uri");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_artefatos");

                    b.HasIndex("EtapaId")
                        .HasDatabaseName("ix_artefatos_etapa_id");

                    b.ToTable("artefatos", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_autores");

                    b.ToTable("autores", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_limite");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcao_id");

                    b.Property<Guid>("LivroId")
                        .HasColumnType("uuid")
                        .HasColumnName("livro_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("observacao");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_etapas");

                    b.HasIndex("FuncaoId")
                        .HasDatabaseName("ix_etapas_funcao_id");

                    b.HasIndex("LivroId")
                        .HasDatabaseName("ix_etapas_livro_id");

                    b.ToTable("etapas", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.EtapaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FluxoProducaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fluxo_producao_id");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcao_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacaoPadrao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("observacao_padrao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("PrazoDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("prazo_dias");

                    b.HasKey("Id")
                        .HasName("pk_etapas_template");

                    b.HasIndex("FluxoProducaoId")
                        .HasDatabaseName("ix_etapas_template_fluxo_producao_id");

                    b.HasIndex("FuncaoId")
                        .HasDatabaseName("ix_etapas_template_funcao_id");

                    b.ToTable("etapas_template", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.FluxoProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_fluxos_producao");

                    b.ToTable("fluxos_producao", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Funcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_funcoes");

                    b.ToTable("funcoes", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<int>("CurrentEtapaIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_etapa_index");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid?>("FluxoProducaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fluxo_producao_id");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_livros");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_livros_autor_id");

                    b.ToTable("livros", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Terceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcao_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_terceiros");

                    b.HasIndex("FuncaoId")
                        .HasDatabaseName("ix_terceiros_funcao_id");

                    b.ToTable("terceiros", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Todos.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveType")
                        .HasColumnType("integer")
                        .HasColumnName("active_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Types")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("types");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Artefato", b =>
                {
                    b.HasOne("CapituloZero.Domain.Editora.Entities.Etapa", null)
                        .WithMany("Artefatos")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artefatos_etapas_etapa_id");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Etapa", b =>
                {
                    b.HasOne("CapituloZero.Domain.Editora.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_funcoes_funcao_id");

                    b.HasOne("CapituloZero.Domain.Editora.Entities.Livro", null)
                        .WithMany("Etapas")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_livros_livro_id");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.EtapaTemplate", b =>
                {
                    b.HasOne("CapituloZero.Domain.Editora.Entities.FluxoProducao", null)
                        .WithMany("Etapas")
                        .HasForeignKey("FluxoProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_etapas_template_fluxos_producao_fluxo_producao_id");

                    b.HasOne("CapituloZero.Domain.Editora.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_etapas_template_funcoes_funcao_id");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Livro", b =>
                {
                    b.HasOne("CapituloZero.Domain.Editora.Entities.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_livros_autores_autor_id");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Terceiro", b =>
                {
                    b.HasOne("CapituloZero.Domain.Editora.Entities.Funcao", "Funcao")
                        .WithMany("Terceiros")
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_terceiros_funcoes_funcao_id");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("CapituloZero.Domain.Todos.Entities.TodoItem", b =>
                {
                    b.HasOne("CapituloZero.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Autor", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Etapa", b =>
                {
                    b.Navigation("Artefatos");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.FluxoProducao", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Funcao", b =>
                {
                    b.Navigation("Terceiros");
                });

            modelBuilder.Entity("CapituloZero.Domain.Editora.Entities.Livro", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
